Repository jfrog/jfrog-client-js, pull requests merged in 2023-03, with the labels that each got.

#73 Fix Axios issue when using http proxy agent
  package-lock.json
  package.json
  src/HttpClient.ts
  test/tests/HttpClient.spec.ts
Labels: bug

#77 Update automation scripts
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  release/pipelines.release.yml
Labels: ignore for release

#78 Add delay and log when retrying requests
  src/Artifactory/ArtifactoryClient.ts
  src/BaseLogger.ts
  src/HttpClient.ts
  src/Xray/XrayClient.ts
Labels: improvement
